In [112]:
# Load a data matrix into python
import pandas as pd
import numpy as np

# Load the data
df = pd.read_csv('sample_data.csv')

# If you need the data as a numpy array
matrix = df.values
df


TBIRTH_YEAR  RHISPANIC  RRACE  EEDUC  MS  EGENID_BIRTH  THHLD_NUMPER  \
0             1973          1      1      7   1             1             4   
1             1945          1      1      6   3             2             1   
2             1975          1      1      7   1             2             5   
3             1986          1      1      7   1             2             3   
4             1948          1      1      5   1             1             2   
...            ...        ...    ...    ...  ..           ...           ...   
61448         1960          1      1      5   1             1             2   
61449         1972          1      1      6   1             2             2   
61450         1979          1      1      6   1             2             2   
61451         1984          1      1      6   1             2             3   
61452         1970          1      1      4   1             2             2   

       THHLD_NUMKID  THHLD_NUMADLT  KIDS_LT5Y  ...  CURFOODSUF  CHILDFOOD  \
0                 0              4        -88  ...           2        -88   
1                 0              1        -88  ...           1        -88   
2                 3              2        -99  ...           1        -88   
3                 1              2          1  ...           1        -88   
4                 0              2        -88  ...           2        -88   
...             ...            ...        ...  ...         ...        ...   
61448             0              2        -88  ...           1        -88   
61449             0              2        -88  ...           1        -88   
61450             0              2        -88  ...           1        -88   
61451             1              2          1  ...           1        -88   
61452             0              2        -88  ...           2        -88   

       TENURE  ENERGY  INCOME  EST_ST  EST_MSA  PRIVHLTH  PUBHLTH  REGION  
0           2       1       6      34  35620.0         1        2       1  
1           2       3       2       8      NaN         1        1       4  
2           2       4       8      51  47900.0         1        2       2  
3           1       4       6      20      NaN         1        2       3  
4           1       4       5       1      NaN         1        1       2  
...       ...     ...     ...     ...      ...       ...      ...     ...  
61448       1       4       7      37      NaN         1        2       2  
61449       2       4       8      36  35620.0         1        2       1  
61450       2       4       8      51  47900.0         1        2       2  
61451       2       4       7      41      NaN         1        2       4  
61452       2       4       6       8      NaN         1        2       4  

[61453 rows x 33 columns]

In [116]:
# Randomly select 10 rows from the matrix without replacement to create a subset  -- 20 points
subset = matrix[np.random.choice(matrix.shape[0], size=10, replace=False)]
subset

array([[ 1.991e+03,  1.000e+00,  1.000e+00,  5.000e+00,  1.000e+00,
         1.000e+00,  4.000e+00,  2.000e+00,  2.000e+00,  1.000e+00,
         1.000e+00, -9.900e+01,  1.000e+00,  2.000e+00,  2.000e+00,
         1.000e+00,  2.000e+00,  1.000e+00,  1.000e+00,  1.000e+00,
         2.000e+00,  1.000e+00,  2.000e+00,  2.000e+00,  3.000e+00,
         2.000e+00,  4.000e+00,  8.000e+00,  6.000e+00,        nan,
         1.000e+00,  2.000e+00,  4.000e+00],
       [ 1.944e+03,  1.000e+00,  1.000e+00,  7.000e+00,  2.000e+00,
         2.000e+00,  1.000e+00,  0.000e+00,  1.000e+00, -8.800e+01,
        -8.800e+01, -8.800e+01,  1.000e+00,  2.000e+00,  1.000e+00,
         1.000e+00,  2.000e+00,  2.000e+00, -8.800e+01,  1.000e+00,
         2.000e+00,  1.000e+00,  2.000e+00,  2.000e+00, -8.800e+01,
         1.000e+00,  4.000e+00,  2.000e+00,  1.900e+01,        nan,
         1.000e+00,  1.000e+00,  3.000e+00],
       [ 1.997e+03,  1.000e+00,  1.000e+00,  3.000e+00,  5.000e+00,
         1.000e+00,  2.000

In [115]:
# (10 points) Select all rows from the matrix where the value in the first column is greater than 5  -- 20 points
subset = matrix[matrix[:, 0] > 5]
subset

array([[1.973e+03, 1.000e+00, 1.000e+00, ..., 1.000e+00, 2.000e+00,
        1.000e+00],
       [1.945e+03, 1.000e+00, 1.000e+00, ..., 1.000e+00, 1.000e+00,
        4.000e+00],
       [1.975e+03, 1.000e+00, 1.000e+00, ..., 1.000e+00, 2.000e+00,
        2.000e+00],
       ...,
       [1.979e+03, 1.000e+00, 1.000e+00, ..., 1.000e+00, 2.000e+00,
        2.000e+00],
       [1.984e+03, 1.000e+00, 1.000e+00, ..., 1.000e+00, 2.000e+00,
        4.000e+00],
       [1.970e+03, 1.000e+00, 1.000e+00, ..., 1.000e+00, 2.000e+00,
        4.000e+00]])

In [114]:
# Retrieve one row (sample) from the matrix based on its index, in this case, the first row (index 0)  -- 10 points
subset = matrix[0]
subset


array([ 1.973e+03,  1.000e+00,  1.000e+00,  7.000e+00,  1.000e+00,
        1.000e+00,  4.000e+00,  0.000e+00,  4.000e+00, -8.800e+01,
       -8.800e+01, -8.800e+01,  2.000e+00, -8.800e+01, -8.800e+01,
        1.000e+00,  2.000e+00,  1.000e+00,  1.000e+00,  1.000e+00,
        1.000e+00,  1.000e+00,  4.000e+00,  2.000e+00, -8.800e+01,
        2.000e+00,  1.000e+00,  6.000e+00,  3.400e+01,  3.562e+04,
        1.000e+00,  2.000e+00,  1.000e+00])

In [113]:
# Retrieve one column (feature) from the matrix based on its index, in this case, the first column (index 0)  -- 10 points
subset = matrix[:, 0]
subset

array([1973., 1945., 1975., ..., 1979., 1984., 1970.])

In [79]:
# Apply feature normalization to the matrix using StandardScaler, which standardizes each feature to have a mean of 0 and a standard deviation of 1
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
normalized_matrix = scaler.fit_transform(matrix)



In [80]:
# Perform min-max normalization on the matrix, scaling each feature to a range of 0 to 1 by subtracting the minimum and dividing by the range (max - min) for each column  -- 20 points



In [81]:
# Calculate and print the cosine similarity between two samples from the matrix by subtracting the cosine distance from 1  -- 10 points
from scipy.spatial.distance import cosine
sample1 = matrix[0]
sample2 = matrix[1]




In [82]:
# Calculate and print the dot of 2 matrix   -- 10 points
A_a = np.array([[1, 2], [4, 5], [7, 8]])
B_a = np.array([[1, 1, 0], [0, 1, 1]])


In [83]:
A_b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B_b = np.array([[1, 1, 0], [0, 1, 1], [1, 0, 1]])
